version: '3'

services:
  app:
    image: url-shortener
    container_name: url-shortener
    ports:
      - 8080:8080
    networks:
      - url-shortener-network
    environment:
      PostgreSqlConnection: Server=postgres-db;Port=5432;Database=url-shortener;User Id=postgres;Password=postgres
      RedisConnection: redis-cache
    command: ["dotnet", "ef", "database update"]

  postgres-db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      - url-shortener-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url-shortener

  redis-cache:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge
